---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: hellow-world-pipeline-trigger
spec:
  bindings:
  - name: username
    value: $(body.username)
  template:
    ref: hellow-world-pipeline-template
