---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hellow-world-eventlistener
spec:
  serviceAccountName: "tekton-triggers-example-sa"
  triggers:
  - bindings:
    - ref: hellow-world-pipeline-binding
    template:
      ref: hellow-world-pipeline-template