---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: phellow-world-ipeline-template
spec:
  params:
  - name: gitrevision
    description: The username
    default: Tekton
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: hello-world-run-
    spec:
      pipelineRef:
        name: hello-world
      params:
      - name: username
        value: $(params.username)
