---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener
spec:
  serviceAccountName: "tekton-triggers-example-sa"
  triggers:
  - bindings:
    - ref: pipeline-binding
    template:
      ref: pipeline-template